### ISSUE TITLE
3D Sculpting

### ISSUE THREAD

**Issue by elkhalafy** [johtela/Compose3D#1]
Hello, 

Can you support 3d sculpting functions and 3d modelling functions In Compose3D ?

**Comment by johtela** [comment]
Hi,

The main modelling functions currently are in the Geometry namespace. There are 2D primitives like rectangles, circles and paths (B-splines). Using extrusion or lathe functions those can be turned into 3D objects. See the ComposeTester/FighterGeometry class for an example how to use these functions to create a complex model. Simpler examples can be found in ComposeTester/Geometries class.

At some point I intend to document the modelling functionality, but right now I am actually working on procedural texture generation with OpenCL.

Regards,
Tommi

**Comment by elkhalafy** [comment]
Thank you, 
but even 3d sculpting or just limited 3d modelling functions like extrude, bevel, etc.. ?

Thank you.

**Comment by johtela** [comment]
If by sculpting you mean things like subdivision surfaces, constructive solid geometry, or even voxels, those things are not currently in scope for Compose3D. It uses the classic mesh model to define geometrical objects. It contains some of the basic operations found in 3D modelling software like Blender or Sketchup. In fact, one of the original goals of my project was to define a small but sufficient set of operations which would allow to do fairly complex mesh modelling in code. In other words; to eliminate the need of using interactive modelling tools. 

The main idea is that the models are composed from simple primitives in a constructive manner, without directly manipulating the vertices but applying different modifiers and transformations. This allows one to change the parameters of any intermediate stage while keeping the structure of a model intact. Procedural generation of meshes is much easier to do this way. Of course the approach has its limits, but you can get surprisingly far by building your 3D objects like this.

Adding sculpting functions like subdivision surfaces would be an interesting challenge, but currently they are not in my plans. As I said, right now I am focusing on procedural texture generation. Maybe in the future I will experiment with the concepts though, who knows...

-Tommi

**Comment by elkhalafy** [comment]
Thank you Tommi

Really I'm looking for library for .NET That help to create 3d modelling with easier way, and your library wonderful for beginners like me, as I know 3d sculpting using dynamic subdivision, There are project on web for WebGL 1.x and 2.0 That Called ( SculptGL ) and source code here on github, I'm looking for library like your own library that support 3d sculpting and 3d modelling functions from OpenGL 2.1 to higher, I know as you said you focus on texture Generation and I waiting for 3d sculpting functions and 3d modelling too in near future and I hope keep development that library cause really I like it and focus on Higher classes or APIs for beginners like me to help quickly build Graphics Apps faster... 

I hope from you Build It As DLL Library Please for .NET 4.0 and Another build for .NET 4.5 and I hope add email for you to anyone want to add his opinion for your Library to easily contact you..

Thank you


elkhalafy - EG.

**Comment by elkhalafy** [comment]
Can you make simple project for 3d sculpting ??
